name: connectycube_flutter_call_kit
description: A Kortobaa flutter repo forked from connectycube plugin for displaying call screen when app in background or terminated.
version: 3.0.0
homepage: https://github.com/salamaEnigma/flutter-callkit
issue_tracker: https://github.com/salamaEnigma/flutter-callkit/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.connectycube.flutter.connectycube_flutter_call_kit
        pluginClass: ConnectycubeFlutterCallKitPlugin
      ios:
        pluginClass: ConnectycubeFlutterCallKitPlugin